"""Initial migration.

Revision ID: e8e957662ac0
Revises: 
Create Date: 2024-09-23 02:52:09.754056

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import table, column
from sqlalchemy import String, Integer
from werkzeug.security import generate_password_hash
from sqlalchemy.engine import reflection

# revision identifiers, used by Alembic.
revision = 'e8e957662ac0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    conn = op.get_bind()
    inspector = reflection.Inspector.from_engine(conn)
    tables = inspector.get_table_names()

    if 'user' not in tables:
        op.create_table('user',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('username', sa.String(length=150), nullable=False),
            sa.Column('password', sa.String(length=150), nullable=False),
            sa.Column('role', sa.String(length=50), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('username')
        )

    if "vm" not in tables:
        op.create_table('vm',
            sa.Column('id', sa.Integer(), nullable=False),
            sa.Column('name', sa.String(length=100), nullable=False),
            sa.Column('owner_id', sa.Integer(), nullable=False),
            sa.Column('status', sa.String(length=50), nullable=False),
            sa.Column('container_id', sa.String(length=100), nullable=False),
            sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
            sa.PrimaryKeyConstraint('id')
        )
    # ### end Alembic commands ###

    # Add user 'dmore' with hashed password 'password'
    user_table = table('user',
        column('username', String),
        column('password', String),
        column('role', String)
    )

    op.bulk_insert(user_table,
        [
            {'username': 'dmore', 'password': generate_password_hash('password', method='sha256'), 'role': 'user'}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vm')
    op.drop_table('user')
    # ### end Alembic commands ###
